### ISSUE TITLE
Add support to transaction

### ISSUE THREAD

**Issue by victorLessa** [ks-labs/adonis-audit#3]
Possuo um código semelhante ao apresentado embaixo utilizando transaction, porém o audit não considera o trx do transaction para realizar um rollback caso necessario

```js
 const trx = await Database.beginTransaction()
    let entity
    try {
      entity = await Entity.audit().create(entityData, trx)
      await entity.users().sync(users, null, trx)
      ...
```

Seria interessante possuir uma possibilidade de usar como:

```js
 const trx = await Database.beginTransaction()
    let entity
    try {
      entity = await Entity.audit(trx).create(entityData, trx)
      await entity.users().sync(users, null, trx)
      ...
```

Da mesma forma que o Adonis usa para o knexjs

**Comment by vinicioslc** [comment]
These improvements are added and specified into [documentation](https://github.com/ks-labs/adonis-audit/blob/master/README.md#transaction-support)

If i had miss something 
or has something to improve/add please reopen the issue

**Comment by victorLessa** [comment]
It works for me.
